name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  is-prerelease:
    name: Determine if this is a prerelease
    uses: Falcons-Creative-Group/ci-cd-workflows/.github/workflows/prerelease-check.yml@main
    with:
        default-branch: 'main'

  release-and-deploy:
    name: Create (pre)release and deploy
    needs: is-prerelease
    uses: Falcons-Creative-Group/ci-cd-workflows/.github/workflows/release-to-github.yml@main
    secrets:
      sg-api-key: ${{ secrets.SG_SCRIPT_API_KEY }}
    with:
        is-prerelease: ${{ fromJSON(needs.is-prerelease.outputs.is-prerelease) }}
